name: Continuous Integration

# Run on pushes to any branch and on pull_request events
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.11]

    steps:
      # 1. Check out your code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up the Python version from the matrix
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # 3. Install your package in editable mode + dev dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # if you have a requirements-dev.txt:
          pip install -r requirements-dev.txt
          # or if you use poetry:
          # pip install poetry
          # poetry install --with dev

      # 4. Lint with flake8 (or your preferred linter)
      - name: Lint with flake8
        run: |
          # fail on any lint errors
          flake8 .

      # 5. (Optional) Type-check with mypy
      - name: Type-check with mypy
        run: |
          mypy deeplotyper

      # 6. Run your test suite
      - name: Run tests with pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q
